-- Query 2 — Funcionários por Região (com localização)
-- EMPLOYEES com LEFT JOIN em DEPARTMENTS, LOCATIONS, COUNTRIES e REGIONS.

SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    HIRE_DATE,
    JOB_ID,
    SALARY,
    COMMISSION_PCT,
    MANAGER_ID,
    DEPARTMENT_ID
FROM
    HR.EMPLOYEES;


SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    MANAGER_ID,
    LOCATION_ID
FROM
    HR.DEPARTMENTS;


SELECT
    LOCATION_ID,
    STREET_ADDRESS,
    POSTAL_CODE,
    CITY,
    STATE_PROVINCE,
    COUNTRY_ID
FROM
    HR.LOCATIONS;


SELECT
    COUNTRY_ID,
    COUNTRY_NAME,
    REGION_ID
FROM
    HR.COUNTRIES;

SELECT
    REGION_ID,
    REGION_NAME
FROM
    HR.REGIONS;


SELECT 
FUNCIONARIOS.EMPLOYEE_ID, 
FUNCIONARIOS.FIRST_NAME, 
FUNCIONARIOS.LAST_NAME,
FUNCIONARIOS.SALARY, 
DEPARTAMENTOS.DEPARTMENT_NAME,
LOCALIZACAO.STREET_ADDRESS,
LOCALIZACAO.CITY,
LOCALIZACAO.STATE_PROVINCE,
continente.COUNTRY_NAME,
regiao.REGION_NAME
FROM HR.EMPLOYEES funcionarios
LEFT JOIN HR.DEPARTMENTS departamentos
ON funcionarios.DEPARTMENT_ID = departamentos.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS localizacao
ON departamentos.LOCATION_ID = localizacao.LOCATION_ID
LEFT JOIN HR.COUNTRIES continente
ON localizacao.COUNTRY_ID = continente.COUNTRY_ID
LEFT JOIN HR.REGIONS regiao 
ON continente.REGION_ID = regiao.REGION_ID
WHERE regiao.REGION_NAME IS NOT NULL
ORDER BY regiao.REGION_NAME

